In [1]:
import pandas as pd

In [20]:
pd.set_option('display.max_columns', 30)  # or 1000
pd.set_option('display.max_rows', 30)  # or 1000
pd.set_option('display.max_colwidth', 30)  # or 199

In [21]:
faund_data = pd.read_csv('data/final_faundamental_info.csv')

In [22]:
predictor_data= pd.read_csv('data/Class.csv')

In [23]:
timed_data= pd.read_csv('timed_price_data.csv')

In [24]:
companies_and_predictor= pd.merge(faund_data,predictor_data,on='Ticker')

In [25]:
companies_and_predictor

,Unnamed: 0,Ticker,52WeekChange,SandP52WeekChange,address1,address2,algorithm,annualHoldingsTurnover,annualReportExpenseRatio,ask,askSize,averageDailyVolume10Day,averageDailyVolume3Month,averageVolume,averageVolume10days,...,trailingPE,twoHundredDayAverage,underlyingExchangeSymbol,underlyingSymbol,uuid,volume,volume24Hr,volumeAllCurrencies,website,yield,ytdReturn,zip,COVID BEHAVIOUR,COVID DEPENDANCY,CLASS
0,0,AAL,0.553405,0.24252,1 Skyview Drive,NaN,NaN,NaN,NaN,20.07,21500.0,28632057.0,NaN,31961979.0,28632057.0,...,NaN,21.483670,NaN,NaN,NaN,21691045.0,NaN,NaN,http://www.aa.com,NaN,NaN,76155,1110,7,1
1,1,AAPL,0.148714,0.24252,One Apple Park Way,NaN,NaN,NaN,NaN,142.81,2200.0,80918485.0,NaN,79762242.0,80918485.0,...,32.119576,137.852740,NaN,NaN,8b10e4ae-9eeb-3684-921a-9a...,58773155.0,NaN,NaN,http://www.apple.com,NaN,NaN,95014,1101,3,0
2,2,ABC,NaN,NaN,1 West First Avenue,NaN,NaN,NaN,NaN,119.34,1000.0,853085.0,NaN,809303.0,853085.0,...,NaN,119.068700,NaN,NaN,NaN,665127.0,NaN,NaN,http://www.amerisourceberg...,NaN,NaN,19428-1800,11111,2,0
3,3,ADI,NaN,NaN,One Analog Way,NaN,NaN,NaN,NaN,168.76,800.0,3531485.0,NaN,4622598.0,3531485.0,...,40.243435,163.640080,NaN,NaN,d98d9168-137c-3f9c-afb4-ad...,3145920.0,NaN,NaN,http://www.analog.com,NaN,NaN,01887,11110,6,1
4,4,ADM,NaN,NaN,77 West Wacker Drive,Suite 4600,NaN,NaN,NaN,64.00,1400.0,2206300.0,NaN,2413278.0,2206300.0,...,15.429058,61.523598,NaN,NaN,NaN,2103471.0,NaN,NaN,http://www.adm.com,NaN,NaN,60601,11110,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,469,XYL,NaN,NaN,1 International Drive,NaN,NaN,NaN,NaN,121.49,800.0,993871.0,NaN,759921.0,993871.0,...,72.736530,120.734245,NaN,NaN,0b3e315c-d662-3b77-8ee7-b4...,623655.0,NaN,NaN,http://www.xylem.com,NaN,NaN,10573,1101,3,0
420,470,YUM,NaN,NaN,1441 Gardiner Lane,NaN,NaN,NaN,NaN,129.20,2200.0,1870200.0,NaN,1538517.0,1870200.0,...,33.000800,121.868850,NaN,NaN,b8fcb647-8cfb-3592-a2bf-1d...,918016.0,NaN,NaN,http://www.yum.com,NaN,NaN,40213,1101,3,0
421,471,ZBH,NaN,NaN,345 East Main Street,NaN,NaN,NaN,NaN,151.00,1100.0,1035642.0,NaN,1492907.0,1035642.0,...,53.796770,158.627200,NaN,NaN,2f40c775-c890-3bae-80b9-c6...,498881.0,NaN,NaN,http://www.zimmerbiomet.com,NaN,NaN,46580,11110,3,0
422,472,ZION,NaN,NaN,One South Main Street,NaN,NaN,NaN,NaN,65.47,900.0,1158471.0,NaN,1298614.0,1158471.0,...,12.903028,55.774532,NaN,NaN,687d0c8c-3762-3a32-b59e-6e...,673095.0,NaN,NaN,http://www.zionsbancorpora...,NaN,NaN,84133-1109,1111,7,1
423,473,ZTS,NaN,NaN,10 Sylvan Way,NaN,NaN,NaN,NaN,204.00,900.0,1722457.0,NaN,1505818.0,1722457.0,...,53.336930,186.854600,NaN,NaN,e8724ae7-5c8b-3a4a-927d-2a...,1085564.0,NaN,NaN,http://www.zoetis.com,NaN,NaN,07054,11101,2,0

In [26]:
del companies_and_predictor['Unnamed: 0']

In [28]:
extended_dataframe_with_all= pd.merge(companies_and_predictor,timed_data,on='Ticker')

In [35]:
selected_dataframe=extended_dataframe_with_all[['Ticker','sector','city','industry','profitMargins','priceToBook','bookValue','shortRatio','revenuePerShare','operatingMargins','forwardEps','heldPercentInstitutions','heldPercentInsiders','marketCap','profitMargins','volume','totalDebt','totalCash','beta','totalCashPerShare','enterpriseValue','floatShares','volume','numberOfAnalystOpinions','COVID BEHAVIOUR','COVID DEPENDANCY','CLASS', '2020-03-15 00:00:00',
       '2020-04-10 00:00:00', '2020-05-10 00:00:00', '2020-09-10 00:00:00',
       '2021-01-01 00:00:00', '2021-02-20 00:00:00', '2021-05-15 00:00:00',
       '2021-09-10 00:00:00']]

In [42]:
selected_dataframe.isnull().sum()

Ticker                 0
sector                 2
city                   2
industry               2
profitMargins          2
                      ..
2020-09-10 00:00:00    0
2021-01-01 00:00:00    0
2021-02-20 00:00:00    0
2021-05-15 00:00:00    0
2021-09-10 00:00:00    0
Length: 35, dtype: int64

In [43]:
# dropping companies with null values

In [40]:
final4=selected_dataframe[selected_dataframe.isnull()==False]

In [51]:
final4.to_csv('complete_extended_dataset.csv')

In [50]:
final4

,Ticker,sector,city,industry,profitMargins,priceToBook,bookValue,shortRatio,revenuePerShare,operatingMargins,forwardEps,heldPercentInstitutions,heldPercentInsiders,marketCap,profitMargins,...,enterpriseValue,floatShares,volume,numberOfAnalystOpinions,COVID BEHAVIOUR,COVID DEPENDANCY,CLASS,2020-03-15 00:00:00,2020-04-10 00:00:00,2020-05-10 00:00:00,2020-09-10 00:00:00,2021-01-01 00:00:00,2021-02-20 00:00:00,2021-05-15 00:00:00,2021-09-10 00:00:00
1,AAPL,Technology,Cupertino,Consumer Electronics,0.25004,36.810920,3.882,1.28,20.610,0.28788,5.68,0.58694,0.00073,2.384658e+12,0.25004,...,2.435956e+12,1.651297e+10,58773155.0,42.0,1101,3,0,66.459000,65.997499,85.249498,113.907499,129.927500,129.922000,129.881996,153.710003
3,ADI,Technology,Wilmington,Semiconductors,0.26153,5.111401,32.989,2.22,17.631,0.32747,6.96,0.70573,0.00215,6.219161e+10,0.26153,...,6.794875e+10,3.667194e+08,3145920.0,22.0,11110,6,1,93.972002,98.060001,120.808000,114.115000,147.920002,160.274002,167.180002,166.422501
4,ADM,Consumer Defensive,Chicago,Farm Products,0.03087,1.697556,37.283,1.94,133.434,0.03542,4.45,0.81336,0.00498,3.540228e+10,0.03087,...,4.489559e+10,5.568941e+08,2103471.0,13.0,11110,3,0,34.210000,36.455000,40.928000,46.045000,51.005000,56.151999,64.356001,59.692499
5,ADP,Industrials,Roseland,Staffing & Employment Serv...,0.17317,15.405769,13.382,2.53,35.199,0.22361,7.30,0.81256,0.00126,8.772479e+10,0.17317,...,8.809349e+10,4.224544e+08,1002526.0,18.0,1101,4,0,139.933998,139.415001,152.975998,134.622498,170.387501,169.200003,198.515997,202.837502
6,ADSK,Technology,San Rafael,Software—Application,0.33315,54.384870,5.129,2.06,17.740,0.17001,6.87,0.91800,0.00191,6.132496e+10,0.33315,...,6.357918e+10,2.196723e+08,797433.0,19.0,11111,6,1,152.197998,156.282501,229.262000,228.204998,301.687500,302.911999,276.967999,287.282494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,XRX,Technology,Norwalk,Information Technology Ser...,0.04125,0.744790,28.263,4.32,36.313,0.07361,2.22,0.84632,0.05560,4.040484e+09,0.04125,...,6.346144e+09,1.375856e+08,624804.0,5.0,110,5,1,24.868000,18.985000,17.942000,18.845000,22.925000,23.742000,24.502000,21.220000
419,XYL,Industrials,Rye Brook,Specialty Industrial Machi...,0.07404,7.444384,16.317,4.88,28.861,0.12038,3.28,0.91411,0.01043,2.186970e+10,0.07404,...,2.573870e+10,1.793523e+08,623655.0,12.0,1101,3,0,70.404001,67.452499,67.808001,82.832500,101.205000,98.638002,116.589999,134.759998
421,ZBH,Healthcare,Warsaw,Medical Devices,0.11614,2.455750,59.717,2.10,37.955,0.17037,8.77,0.92493,0.00081,3.057388e+10,0.11614,...,3.841205e+10,2.085794e+08,498881.0,26.0,11110,3,0,104.266000,105.372501,130.251999,139.090000,155.827499,158.553998,158.517999,144.719997
422,ZION,Financial Services,Salt Lake City,Banks—Regional,0.35480,1.411197,44.976,3.92,19.579,0.46765,4.34,0.85528,0.01542,1.039740e+10,0.35480,...,-2.425460e+07,1.596475e+08,673095.0,22.0,1111,7,1,29.154000,28.852500,37.038000,31.737500,44.622499,51.406000,54.112000,57.235001
423,ZTS,Healthcare,Parsippany,Drug Manufacturers—Special...,0.25756,22.985249,8.609,3.03,15.591,0.36212,5.07,0.92700,0.00201,9.394690e+10,0.25756,...,1.007056e+11,4.731574e+08,1085564.0,13.0,11101,2,0,123.158002,127.225000,137.028003,157.277500,165.242496,164.666000,184.600000,207.540001